env:
  global:
    - CC_TEST_REPORTER_ID=dacd365e0c3d85782e5bfa10d8b66f5dd77a13654c8084ffbfa854370d8b27aa

language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

cache: bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: 'bundle exec rspec --format documentation'

after_script:
  - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
